Snyk plugin
blackstork-io/fabric pull request #156
Opened 2024-04-19 07:02 UTC by dobarx

TBD

2024-04-20 11:01 UTC, traut commented on tools/docgen/main.go
> +		snyk.Plugin(version, nil),
we really should make this a dynamic discovery (for our plugins) with the ability to extend the list with additions from a flat file (or something) 😄 just a note, not in this pull request

2024-04-20 11:01 UTC, traut approved these changes

2024-04-22 00:04 UTC, Andrew-Morozko requested changes

2024-04-22 00:04 UTC, Andrew-Morozko commented on internal/snyk/data_snyk_issues_test.go
LGTM, but the tests would require a bit of a rewrite. After we started using default values and `dataspec` the plugins can rely on the default values being present and that required values are non-nil. Manually created `cty.Value`s in tests ignore the default values and required value validation checks.

You can take a look at updated tests for the builtin plugins (in  #152), I've implemented a function to construct hcl from cty.Value and re-parse it with default values/required values checked appropriately.

In future I guess that tests for "errors if required value is missing" are not needed, the `dataspec` validates the data already. And after extracting more validation logic into `dataspec` (like range checks, non empty strings, #158 ) only relatively few niche validation would be made by the plugin code itself.

2024-04-22 09:49 UTC, dobarx commented on internal/snyk/data_snyk_issues_test.go
Ok, I think I will merge it once I rebase it after your PR #152. Since I see it has some utils for these tests.

2024-05-05 06:26 UTC, dobarx commented on internal/snyk/data_snyk_issues_test.go
Updated tests using `testtools` for those spec values. But this did not help much for `snyk` plugin. Default values for most of the args are `nil`. Required checks for args `org_id` & `group_id` does not work with `dataspec` because we require one of these two to be set and there is no such constraint on`dataspec`.

2024-05-07 18:51 UTC, Andrew-Morozko approved these changes

2024-05-14 04:58 UTC, merged